import './globals.css'

export const metadata = {
  title: 'Create Next App', // This will be displayed in the browser tab 
  description: 'My first app generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
